version: 2.1

executors:
  openjdk8-executor:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    executor: openjdk8-executor

    steps:
      - checkout
      - run: gradle build -x test -x detekt

  test:
    executor: openjdk8-executor

    steps:
      - checkout
      - run: gradle test

  detekt:
    executor: openjdk8-executor

    steps:
      - checkout
      - run: gradle detekt

workflows:
  push-workflow:
    jobs:
      - build
      - test
      - detekt
