version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: gradle build

  test:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run: gradle test

workflows:
  push-workflow:
    jobs:
      - build
      - test
